#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sqlalchemy-migrate
Version  : 0.11.0
Release  : 29
URL      : http://pypi.debian.net/sqlalchemy-migrate/sqlalchemy-migrate-0.11.0.tar.gz
Source0  : http://pypi.debian.net/sqlalchemy-migrate/sqlalchemy-migrate-0.11.0.tar.gz
Summary  : Database schema migration for SQLAlchemy
Group    : Development/Tools
License  : MIT
Requires: sqlalchemy-migrate-bin
Requires: sqlalchemy-migrate-python3
Requires: sqlalchemy-migrate-license
Requires: sqlalchemy-migrate-python
Requires: SQLAlchemy
Requires: Tempita
Requires: decorator
Requires: pbr
Requires: six
Requires: sqlparse
BuildRequires : MySQL-python
BuildRequires : Tempita
BuildRequires : buildreq-distutils3
BuildRequires : decorator-python
BuildRequires : extras
BuildRequires : mariadb
BuildRequires : pbr
BuildRequires : pip
BuildRequires : postgresql
BuildRequires : psycopg2
BuildRequires : py
BuildRequires : pytest
BuildRequires : python-mimeparse
BuildRequires : python-mock
BuildRequires : python-subunit
BuildRequires : python3-dev
BuildRequires : scripttest-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : sqlalchemy-migrate
BuildRequires : sqlalchemy-python
BuildRequires : sqlparse
BuildRequires : tempest-lib
BuildRequires : testrepository
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : traceback2

%description
==================

%package bin
Summary: bin components for the sqlalchemy-migrate package.
Group: Binaries
Requires: sqlalchemy-migrate-license

%description bin
bin components for the sqlalchemy-migrate package.


%package license
Summary: license components for the sqlalchemy-migrate package.
Group: Default

%description license
license components for the sqlalchemy-migrate package.


%package python
Summary: python components for the sqlalchemy-migrate package.
Group: Default
Requires: sqlalchemy-migrate-python3

%description python
python components for the sqlalchemy-migrate package.


%package python3
Summary: python3 components for the sqlalchemy-migrate package.
Group: Default
Requires: python3-core

%description python3
python3 components for the sqlalchemy-migrate package.


%prep
%setup -q -n sqlalchemy-migrate-0.11.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532447302
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7  --ignore=py2/lib/migrate/tests/changeset/databases/test_ibmdb2.py || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/sqlalchemy-migrate
cp COPYING %{buildroot}/usr/share/doc/sqlalchemy-migrate/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/migrate
/usr/bin/migrate-repository

%files license
%defattr(-,root,root,-)
/usr/share/doc/sqlalchemy-migrate/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
