#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sqlalchemy-migrate
Version  : 0.11.0
Release  : 26
URL      : http://pypi.debian.net/sqlalchemy-migrate/sqlalchemy-migrate-0.11.0.tar.gz
Source0  : http://pypi.debian.net/sqlalchemy-migrate/sqlalchemy-migrate-0.11.0.tar.gz
Summary  : Database schema migration for SQLAlchemy
Group    : Development/Tools
License  : MIT
Requires: sqlalchemy-migrate-bin
Requires: sqlalchemy-migrate-python
Requires: SQLAlchemy
Requires: Tempita
Requires: decorator
Requires: pbr
Requires: six
Requires: sqlparse
BuildRequires : MySQL-python
BuildRequires : Tempita
BuildRequires : configparser-python
BuildRequires : decorator-python
BuildRequires : extras
BuildRequires : mariadb
BuildRequires : pbr
BuildRequires : pip
BuildRequires : postgresql
BuildRequires : psycopg2
BuildRequires : py
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mimeparse
BuildRequires : python-mock
BuildRequires : python-subunit
BuildRequires : python3-dev
BuildRequires : scripttest-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : sqlalchemy-migrate
BuildRequires : sqlalchemy-python
BuildRequires : sqlparse
BuildRequires : tempest-lib
BuildRequires : testrepository
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : traceback2

%description
This is a database migration repository.
More information at
http://code.google.com/p/sqlalchemy-migrate/

%package bin
Summary: bin components for the sqlalchemy-migrate package.
Group: Binaries

%description bin
bin components for the sqlalchemy-migrate package.


%package python
Summary: python components for the sqlalchemy-migrate package.
Group: Default

%description python
python components for the sqlalchemy-migrate package.


%prep
%setup -q -n sqlalchemy-migrate-0.11.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489092106
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7  --ignore=py2/lib/migrate/tests/changeset/databases/test_ibmdb2.py || :
%install
export SOURCE_DATE_EPOCH=1489092106
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/migrate
/usr/bin/migrate-repository

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
